blueprint:
  name: Sync Lights with Primary Light
  description: >
    Synchronize multiple lights with a designated primary (lead) light. 
    When the primary light's ON/OFF state changes, all other lights will follow.
  domain: automation
  input:
    primary_light:
      name: Primary Light
      description: The main light that triggers the sync.
      selector:
        entity:
          domain: light
    synced_lights:
      name: Lights to Sync
      description: The lights that will follow the primary light (can be multiple).
      selector:
        target:
          entity:
            domain: light

trigger:
  - platform: state
    entity_id: !input primary_light
    to: 'on'
  - platform: state
    entity_id: !input primary_light
    to: 'off'

condition: []

action:
  - choose:
      - conditions:
          - condition: state
            entity_id: !input primary_light
            state: 'on'
        sequence:
          - service: light.turn_on
            target: !input synced_lights
      - conditions:
          - condition: state
            entity_id: !input primary_light
            state: 'off'
        sequence:
          - service: light.turn_off
            target: !input synced_lights

mode: restart
